#### Importamos las librerías
#### Cargamos el .csv y renombramos las columnas
#### Añadimos una columna nueva que llevará el valor 1

In [4]:
import pandas as pd
import json
import re
from sklearn.pipeline import Pipeline
from sklearn.ensemble import IsolationForest
import numpy as np

pcap_data = pd.read_csv('/home/snort/Desktop/ransomware2s.csv')
pcap_data.columns = ['no', 'time', 'rel', 'info', 'ipsrc', 'ipdst', 'proto', 'len']
pcap_data['info'] = "null"
pcap_data.parse_dates=["time"]

pcap_data['num'] = 1
df = pcap_data
df

,no,time,rel,info,ipsrc,ipdst,proto,len,num
0,1,2017-03-20 17:08:53,0s,null,10.3.20.102,37.202.7.169,TCP,66,1
1,2,2017-03-20 17:08:54,0s,null,37.202.7.169,10.3.20.102,TCP,60,1
2,3,2017-03-20 17:08:54,0s,null,10.3.20.102,37.202.7.169,TCP,60,1
3,4,2017-03-20 17:08:54,0s,null,10.3.20.102,37.202.7.169,HTTP,309,1
4,5,2017-03-20 17:08:54,0s,null,37.202.7.169,10.3.20.102,TCP,60,1
5,6,2017-03-20 17:08:54,0s,null,37.202.7.169,10.3.20.102,TCP,582,1
6,7,2017-03-20 17:08:54,0s,null,10.3.20.102,37.202.7.169,TCP,60,1
7,8,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,1407,1
8,9,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,1395,1
9,10,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,66,1
10,11,2017-03-20 17:08:55,1s,null,10.3.20.102,37.202.7.169,TCP,60,1
11,12,2017-03-20 17:08:55,1s,null,10.3.20.102,37.202.7.169,TCP,60,1
12,13,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,1395,1
13,14,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,66,1
14,15,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,904,1
15,16,2017-03-20 17:08:55,1s,null,10.3.20.102,37.202.7.169,TCP,60,1
16,17,2017-03-20 17:08:55,1s,null,10.3.20.102,37.202.7.169,TCP,60,1
17,18,2017-03-20 17:08:55,1s,null,10.3.20.102,92.53.104.78,TCP,66,1
18,19,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,1514,1
19,20,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,450,1
20,21,2017-03-20 17:08:55,1s,null,10.3.20.102,37.202.7.169,TCP,60,1
21,22,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,1407,1
22,23,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,1395,1
23,24,2017-03-20 17:08:55,1s,null,10.3.20.102,37.202.7.169,TCP,60,1
24,25,2017-03-20 17:08:55,1s,null,10.3.20.102,37.202.7.169,TCP,60,1
25,26,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,1395,1
26,27,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,78,1
27,28,2017-03-20 17:08:55,1s,null,37.202.7.169,10.3.20.102,TCP,1407,1
28,29,2017-03-20 17:08:55,1s,null,10.3.20.102,37.202.7.169,TCP,60,1
29,30,2017-03-20 17:08:55,2s,null,37.202.7.169,10.3.20.102,TCP,1395,1
...,...,...,...,...,...,...,...,...,...
2610,2611,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.241,UDP,60,1
2611,2612,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.242,UDP,60,1
2612,2613,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.243,UDP,60,1
2613,2614,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.244,UDP,60,1
2614,2615,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.245,UDP,60,1
2615,2616,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.246,UDP,60,1
2616,2617,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.247,UDP,60,1
2617,2618,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.248,UDP,60,1
2618,2619,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.249,UDP,60,1
2619,2620,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.250,UDP,60,1
2620,2621,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.251,UDP,60,1
2621,2622,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.252,UDP,60,1
2622,2623,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.253,UDP,60,1
2623,2624,2017-03-20 17:09:16,22s,null,10.3.20.102,149.202.251.254,UDP,60,1
2624,2625,2017-03-20 17:09:17,23s,null,10.3.20.102,149.202.251.255,UDP,60,1
2625,2626,2017-03-20 17:09:30,36s,null,10.3.20.102,216.170.119.139,TCP,66,1
2626,2627,2017-03-20 17:09:30,36s,null,216.170.119.139,10.3.20.102,TCP,60,1
2627,2628,2017-03-20 17:09:30,36s,null,10.3.20.102,216.170.119.139,TCP,60,1
2628,2629,2017-03-20 17:09:30,36s,null,10.3.20.102,216.170.119.139,HTTP,415,1
2629,2630,2017-03-20 17:09:30,36s,null,216.170.119.139,10.3.20.102,TCP,60,1
2630,2631,2017-03-20 17:09:31,37s,null,216.170.119.139,10.3.20.102,HTTP,292,1
2631,2632,2017-03-20 17:09:31,37s,null,10.3.20.102,216.170.119.139,TCP,60,1
2632,2633,2017-03-20 17:10:03,1m 9s,null,92.53.104.78,10.3.20.102,TCP,60,1
2633,2634,2017-03-20 17:10:03,1m 9s,null,10.3.20.102,92.53.104.78,TCP,60,1
2634,2635,2017-03-20 17:10:34,1m 40s,null,10.3.20.102,92.53.104.78,TCP,60,1
2635,2636,2017-03-20 17:10:34,1m 40s,null,92.53.104.78,10.3.20.102,TCP,60,1
2636,2637,2017-03-20 17:10:36,1m 42s,null,216.170.119.139,10.3.20.102,TCP,60,1
2637,2638,2017-03-20 17:10:36,1m 42s,null,10.3.20.102,216.170.119.139,TCP,60,1
2638,2639,2017-03-20 17:11:17,2m 24s,null,10.3.20.102,216.170.119.139,TCP,60,1
2639,2640,2017-03-20 17:11:17,2m 24s,null,216.170.119.139,10.3.20.102,TCP,60,1

#### Convertimos la columna time en datetime y en indice
#### Agrupamos por ipdst, proto y data y hacemos un count que irá en una columna nueva llamada count
#### Falta cambiar la columna indice por frequencias de 5 segundos

In [3]:
df['time'] = pd.to_datetime(df['time'])
df.index = df['time']
data = df.copy()

data_group = pd.DataFrame({'count': data.groupby(['ipdst', 'proto', data.index]).size()}).reset_index()
#data_group['count'] = data_group['count'].astype(float)
pd.options.display.float_format = '{:,.0f}'.format
data_group.index = data_group['time']
data_group

data_group2 = data_group.groupby(['ipdst','proto']).resample('5S', on='time').sum().reset_index().dropna()
data_group2
#datafreq1 = data_group.resample("5s")['count'].agg(['sum']).reset_index()
#datafreq1 = data_group.resample("5s").sum()
#datafreq1 = data_group.resample("5s").mean().reset_index()
#datafreq1

                ipdst proto                time  count
0         10.3.20.102  HTTP 2017-03-20 17:08:55      3
7         10.3.20.102  HTTP 2017-03-20 17:09:30      1
8         10.3.20.102   TCP 2017-03-20 17:08:50      3
9         10.3.20.102   TCP 2017-03-20 17:08:55    104
10        10.3.20.102   TCP 2017-03-20 17:09:00    204
16        10.3.20.102   TCP 2017-03-20 17:09:30      2
22        10.3.20.102   TCP 2017-03-20 17:10:00      1
28        10.3.20.102   TCP 2017-03-20 17:10:30      1
29        10.3.20.102   TCP 2017-03-20 17:10:35      1
37        10.3.20.102   TCP 2017-03-20 17:11:15      1
38      149.202.122.0   UDP 2017-03-20 17:09:05      1
39      149.202.122.0   UDP 2017-03-20 17:09:10      1
40      149.202.122.1   UDP 2017-03-20 17:09:05      1
41      149.202.122.1   UDP 2017-03-20 17:09:10      1
42     149.202.122.10   UDP 2017-03-20 17:09:05      1
43     149.202.122.10   UDP 2017-03-20 17:09:10      1
44     149.202.122.11   UDP 2017-03-20 17:09:05      1
45     149.202.122.11   UDP 2017-03-20 17:09:10      1
46     149.202.122.12   UDP 2017-03-20 17:09:05      1
47     149.202.122.12   UDP 2017-03-20 17:09:10      1
48     149.202.122.13   UDP 2017-03-20 17:09:05      1
49     149.202.122.13   UDP 2017-03-20 17:09:10      1
50     149.202.122.14   UDP 2017-03-20 17:09:05      1
51     149.202.122.14   UDP 2017-03-20 17:09:10      1
52     149.202.122.15   UDP 2017-03-20 17:09:05      1
53     149.202.122.15   UDP 2017-03-20 17:09:10      1
54     149.202.122.16   UDP 2017-03-20 17:09:05      1
55     149.202.122.16   UDP 2017-03-20 17:09:10      1
56     149.202.122.17   UDP 2017-03-20 17:09:05      1
57     149.202.122.17   UDP 2017-03-20 17:09:10      1
...               ...   ...                 ...    ...
2453     149.202.64.3   UDP 2017-03-20 17:09:10      1
2454    149.202.64.30   UDP 2017-03-20 17:09:05      1
2455    149.202.64.30   UDP 2017-03-20 17:09:10      1
2456    149.202.64.31   UDP 2017-03-20 17:09:05      1
2457    149.202.64.31   UDP 2017-03-20 17:09:10      1
2458     149.202.64.4   UDP 2017-03-20 17:09:05      1
2459     149.202.64.4   UDP 2017-03-20 17:09:10      1
2460     149.202.64.5   UDP 2017-03-20 17:09:05      1
2461     149.202.64.5   UDP 2017-03-20 17:09:10      1
2462     149.202.64.6   UDP 2017-03-20 17:09:05      1
2463     149.202.64.6   UDP 2017-03-20 17:09:10      1
2464     149.202.64.7   UDP 2017-03-20 17:09:05      1
2465     149.202.64.7   UDP 2017-03-20 17:09:10      1
2466     149.202.64.8   UDP 2017-03-20 17:09:05      1
2467     149.202.64.8   UDP 2017-03-20 17:09:10      1
2468     149.202.64.9   UDP 2017-03-20 17:09:05      1
2469     149.202.64.9   UDP 2017-03-20 17:09:10      1
2470  216.170.119.139  HTTP 2017-03-20 17:09:30      1
2471  216.170.119.139   TCP 2017-03-20 17:09:30      3
2484  216.170.119.139   TCP 2017-03-20 17:10:35      1
2492  216.170.119.139   TCP 2017-03-20 17:11:15      1
2493     37.202.7.169  HTTP 2017-03-20 17:08:50      1
2494     37.202.7.169   TCP 2017-03-20 17:08:50      3
2495     37.202.7.169   TCP 2017-03-20 17:08:55     21
2496     92.53.104.78  HTTP 2017-03-20 17:08:55      2
2497     92.53.104.78  HTTP 2017-03-20 17:09:00      1
2498     92.53.104.78   TCP 2017-03-20 17:08:55     31
2499     92.53.104.78   TCP 2017-03-20 17:09:00     76
2511     92.53.104.78   TCP 2017-03-20 17:10:00      1
2517     92.53.104.78   TCP 2017-03-20 17:10:30      1

[2199 rows x 4 columns]

In [190]:
#data_group = pd.DataFrame({'count': datafreq1.groupby(['ipdst', 'proto', datafreq1.index]).size()}).reset_index()
#data_group
#data_group_sel = data_group[['ipdst', 'proto', 'time']]
#data_group_sel

#data_group1 = pd.DataFrame({'count': data_group_sel.groupby(['ipdst', 'proto', 'time']).size()}).reset_index()
#data_group1.groupby(['ipdst', 'proto', 'time']).count()

In [6]:
data_sel_char1 = data_group2[['count']]
data_sel_char1

data_normalized1 = data_sel_char1.copy()
data_normalized1['count_n'] = (data_sel_char1['count'] - data_sel_char1['count'].min()) / (data_sel_char1['count'].max() - data_sel_char1['count'].min())
data_normalized1

      count  count_n
0         3        0
7         1        0
8         3        0
9       104        1
10      204        1
16        2        0
22        1        0
28        1        0
29        1        0
37        1        0
38        1        0
39        1        0
40        1        0
41        1        0
42        1        0
43        1        0
44        1        0
45        1        0
46        1        0
47        1        0
48        1        0
49        1        0
50        1        0
51        1        0
52        1        0
53        1        0
54        1        0
55        1        0
56        1        0
57        1        0
...     ...      ...
2453      1        0
2454      1        0
2455      1        0
2456      1        0
2457      1        0
2458      1        0
2459      1        0
2460      1        0
2461      1        0
2462      1        0
2463      1        0
2464      1        0
2465      1        0
2466      1        0
2467      1        0
2468      1        0
2469      1        0
2470      1        0
2471      3        0
2484      1        0
2492      1        0
2493      1        0
2494      3        0
2495     21        0
2496      2        0
2497      1        0
2498     31        0
2499     76        0
2511      1        0
2517      1        0

[2199 rows x 2 columns]

In [7]:
datatrain = data_normalized1.iloc[100:110000]
datatrain
iforest = IsolationForest(n_estimators=100, contamination=0.00001, max_samples=256)
iforest.fit(datatrain)

prediction = iforest.predict(data_normalized1)

data_group2['prediction'] = prediction
data_group2

                ipdst proto                time  count  prediction
0         10.3.20.102  HTTP 2017-03-20 17:08:55      3           1
7         10.3.20.102  HTTP 2017-03-20 17:09:30      1           1
8         10.3.20.102   TCP 2017-03-20 17:08:50      3           1
9         10.3.20.102   TCP 2017-03-20 17:08:55    104          -1
10        10.3.20.102   TCP 2017-03-20 17:09:00    204          -1
16        10.3.20.102   TCP 2017-03-20 17:09:30      2           1
22        10.3.20.102   TCP 2017-03-20 17:10:00      1           1
28        10.3.20.102   TCP 2017-03-20 17:10:30      1           1
29        10.3.20.102   TCP 2017-03-20 17:10:35      1           1
37        10.3.20.102   TCP 2017-03-20 17:11:15      1           1
38      149.202.122.0   UDP 2017-03-20 17:09:05      1           1
39      149.202.122.0   UDP 2017-03-20 17:09:10      1           1
40      149.202.122.1   UDP 2017-03-20 17:09:05      1           1
41      149.202.122.1   UDP 2017-03-20 17:09:10      1           1
42     149.202.122.10   UDP 2017-03-20 17:09:05      1           1
43     149.202.122.10   UDP 2017-03-20 17:09:10      1           1
44     149.202.122.11   UDP 2017-03-20 17:09:05      1           1
45     149.202.122.11   UDP 2017-03-20 17:09:10      1           1
46     149.202.122.12   UDP 2017-03-20 17:09:05      1           1
47     149.202.122.12   UDP 2017-03-20 17:09:10      1           1
48     149.202.122.13   UDP 2017-03-20 17:09:05      1           1
49     149.202.122.13   UDP 2017-03-20 17:09:10      1           1
50     149.202.122.14   UDP 2017-03-20 17:09:05      1           1
51     149.202.122.14   UDP 2017-03-20 17:09:10      1           1
52     149.202.122.15   UDP 2017-03-20 17:09:05      1           1
53     149.202.122.15   UDP 2017-03-20 17:09:10      1           1
54     149.202.122.16   UDP 2017-03-20 17:09:05      1           1
55     149.202.122.16   UDP 2017-03-20 17:09:10      1           1
56     149.202.122.17   UDP 2017-03-20 17:09:05      1           1
57     149.202.122.17   UDP 2017-03-20 17:09:10      1           1
...               ...   ...                 ...    ...         ...
2453     149.202.64.3   UDP 2017-03-20 17:09:10      1           1
2454    149.202.64.30   UDP 2017-03-20 17:09:05      1           1
2455    149.202.64.30   UDP 2017-03-20 17:09:10      1           1
2456    149.202.64.31   UDP 2017-03-20 17:09:05      1           1
2457    149.202.64.31   UDP 2017-03-20 17:09:10      1           1
2458     149.202.64.4   UDP 2017-03-20 17:09:05      1           1
2459     149.202.64.4   UDP 2017-03-20 17:09:10      1           1
2460     149.202.64.5   UDP 2017-03-20 17:09:05      1           1
2461     149.202.64.5   UDP 2017-03-20 17:09:10      1           1
2462     149.202.64.6   UDP 2017-03-20 17:09:05      1           1
2463     149.202.64.6   UDP 2017-03-20 17:09:10      1           1
2464     149.202.64.7   UDP 2017-03-20 17:09:05      1           1
2465     149.202.64.7   UDP 2017-03-20 17:09:10      1           1
2466     149.202.64.8   UDP 2017-03-20 17:09:05      1           1
2467     149.202.64.8   UDP 2017-03-20 17:09:10      1           1
2468     149.202.64.9   UDP 2017-03-20 17:09:05      1           1
2469     149.202.64.9   UDP 2017-03-20 17:09:10      1           1
2470  216.170.119.139  HTTP 2017-03-20 17:09:30      1           1
2471  216.170.119.139   TCP 2017-03-20 17:09:30      3           1
2484  216.170.119.139   TCP 2017-03-20 17:10:35      1           1
2492  216.170.119.139   TCP 2017-03-20 17:11:15      1           1
2493     37.202.7.169  HTTP 2017-03-20 17:08:50      1           1
2494     37.202.7.169   TCP 2017-03-20 17:08:50      3           1
2495     37.202.7.169   TCP 2017-03-20 17:08:55     21           1
2496     92.53.104.78  HTTP 2017-03-20 17:08:55      2           1
2497     92.53.104.78  HTTP 2017-03-20 17:09:00      1           1
2498     92.53.104.78   TCP 2017-03-20 17:08:55     31           1
2499     92.53.104.78   TCP 2017-03-20 17:09:00     76          -1
2511     92.53.104.78   TCP 2017-03-20 17:10:00      1           1
2517     92.53.104.78   TCP 2017-03-20 17:10:30      1           1

[2199 rows x 5 columns]

In [8]:
#anomalies = data_group2.loc[data_group2.prediction==-1]
data_group2[(data_group2['prediction'] == -1)]

             ipdst proto                time  count  prediction
9      10.3.20.102   TCP 2017-03-20 17:08:55    104          -1
10     10.3.20.102   TCP 2017-03-20 17:09:00    204          -1
2499  92.53.104.78   TCP 2017-03-20 17:09:00     76          -1